spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/encrypt?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: root

mybatis:
  type-aliases-package: com.hengheng.mybatis.encrypt.typehandler.alias
  type-handlers-package: com.hengheng.mybatis.encrypt.typehandler.handler
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl